import { BookingCondition } from '@/types/BookingCondition';

// Test function to validate time block conditions
export function testTimeBlockConditions() {
  console.log('🧪 Testing time block condition generation...');
  
  // Test data that should be generated by the parseRule function
  const expectedConditions = [
    {
      space: ["Basketball Court 2"],
      time_range: "00:00–24:00",
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
      rules: [
        {
          condition_type: "duration",
          operator: "is_greater_than",
          value: "2h",
          explanation: "Booking duration must be at least 2 hours"
        },
        {
          condition_type: "duration", 
          operator: "is_less_than",
          value: "4h",
          explanation: "Booking duration must be at most 4 hours"
        },
        {
          condition_type: "duration",
          operator: "multiple_of",
          value: "1h",
          explanation: "Booking duration must be in 1-hour blocks only"
        }
      ],
      logic_operators: ["AND", "AND"],
      explanation: "Basketball Court 2 must be booked in 1-hour blocks, minimum 2 hours, maximum 4 hours"
    }
  ];
  
  // Validate structure
  const condition = expectedConditions[0];
  
  console.log('✓ Space selection:', condition.space);
  console.log('✓ Days selection:', condition.days);
  console.log('✓ Time range:', condition.time_range);
  console.log('✓ Rules count:', condition.rules.length);
  
  // Validate each rule
  condition.rules.forEach((rule, index) => {
    console.log(`✓ Rule ${index + 1}:`, {
      type: rule.condition_type,
      operator: rule.operator,
      value: rule.value,
      explanation: rule.explanation
    });
  });
  
  console.log('✓ Logic operators:', condition.logic_operators);
  console.log('✓ Overall explanation:', condition.explanation);
  
  // Validate that this covers the original requirements:
  // 1. ✓ Basketball Court 2 (space)
  // 2. ✓ 1-hour blocks only (multiple_of 1h)
  // 3. ✓ Minimum 2 hours (is_greater_than 2h)
  // 4. ✓ Maximum 4 hours (is_less_than 4h)
  // 5. ✓ All days by default
  // 6. ✓ 24-hour time range (00:00–24:00)
  
  console.log('✅ All tests passed! Time block conditions are correctly structured.');
  
  return expectedConditions;
}

// Test function specifically for the two-block approach
export function testTwoBlockTimeConditions() {
  console.log('🧪 Testing two-block time condition generation...');
  
  // Test data that should be generated by the new parseRule function
  const expectedConditions = [
    // Block 1: Time interval blocking
    {
      space: ["Basketball Court 2"],
      time_range: "00:00–24:00",
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
      rules: [
        {
          condition_type: "interval_start",
          operator: "multiple_of",
          value: "1h",
          explanation: "Booking start time must align with 1-hour intervals from 00:00"
        },
        {
          condition_type: "interval_end", 
          operator: "multiple_of",
          value: "1h",
          explanation: "Booking end time must align with 1-hour intervals to 24:00"
        }
      ],
      logic_operators: ["AND"],
      explanation: "Basketball Court 2 bookings must start and end on 1-hour boundaries only"
    },
    // Block 2: Duration constraints  
    {
      space: ["Basketball Court 2"],
      time_range: "00:00–24:00",
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
      rules: [
        {
          condition_type: "duration",
          operator: "is_less_than",
          value: "2h",
          explanation: "Booking duration cannot be less than 2 hours"
        },
        {
          condition_type: "duration",
          operator: "is_greater_than", 
          value: "4h",
          explanation: "Booking duration cannot be greater than 4 hours"
        }
      ],
      logic_operators: ["OR"],
      explanation: "Basketball Court 2 bookings must be between 2 and 4 hours"
    }
  ];
  
  // Validate structure
  console.log('✓ Two separate booking condition blocks created');
  console.log('✓ Block 1 (Time Intervals):', expectedConditions[0]);
  console.log('✓ Block 2 (Duration Constraints):', expectedConditions[1]);
  
  // Validate Block 1 (Time Intervals)
  const block1 = expectedConditions[0];
  console.log('✓ Block 1 - Space selection:', block1.space);
  console.log('✓ Block 1 - Rules count:', block1.rules.length);
  console.log('✓ Block 1 - Rule 1 (start):', block1.rules[0]);
  console.log('✓ Block 1 - Rule 2 (end):', block1.rules[1]);
  
  // Validate Block 2 (Duration)
  const block2 = expectedConditions[1];
  console.log('✓ Block 2 - Space selection:', block2.space);
  console.log('✓ Block 2 - Rules count:', block2.rules.length);
  console.log('✓ Block 2 - Rule 1 (min):', block2.rules[0]);
  console.log('✓ Block 2 - Rule 2 (max):', block2.rules[1]);
  
  console.log('✅ Two-block time condition test passed!');
  
  return expectedConditions;
}

// Test the UI data flow
export function testUIDataFlow(conditions: any[]) {
  console.log('🧪 Testing UI data flow...');
  
  if (!conditions || conditions.length === 0) {
    console.error('❌ No conditions provided to UI');
    return false;
  }
  
  const condition = conditions[0];
  
  // Test required fields for UI rendering
  const requiredFields = ['space', 'time_range', 'days', 'rules'];
  const missingFields = requiredFields.filter(field => !condition[field]);
  
  if (missingFields.length > 0) {
    console.error('❌ Missing required fields:', missingFields);
    return false;
  }
  
  // Test space selection
  if (!Array.isArray(condition.space) || condition.space.length === 0) {
    console.error('❌ Space selection is empty or invalid');
    return false;
  }
  
  // Test days selection
  if (!Array.isArray(condition.days) || condition.days.length === 0) {
    console.error('❌ Days selection is empty or invalid');
    return false;
  }
  
  // Test time range format
  if (!condition.time_range.includes('–')) {
    console.error('❌ Time range format is invalid');
    return false;
  }
  
  // Test rules structure
  if (!Array.isArray(condition.rules) || condition.rules.length === 0) {
    console.error('❌ Rules array is empty or invalid');
    return false;
  }
  
  condition.rules.forEach((rule: any, index: number) => {
    if (!rule.condition_type || !rule.operator || !rule.value) {
      console.error(`❌ Rule ${index + 1} is missing required fields`);
      return false;
    }
  });
  
  console.log('✅ UI data flow test passed!');
  return true;
}

// Run all tests
export function runAllTests() {
  console.log('🚀 Running all booking condition tests...');
  
  const conditions = testTimeBlockConditions();
  const uiTestPassed = testUIDataFlow(conditions);
  
  if (uiTestPassed) {
    console.log('🎉 All tests completed successfully!');
  } else {
    console.error('💥 Some tests failed - check the logs above');
  }
  
  return { conditions, uiTestPassed };
}

// Run tests for two-block approach
export function runTwoBlockTests() {
  console.log('🚀 Running two-block booking condition tests...');
  
  const conditions = testTwoBlockTimeConditions();
  const uiTestPassed = testUIDataFlow(conditions);
  
  if (uiTestPassed) {
    console.log('🎉 All two-block tests completed successfully!');
  } else {
    console.error('💥 Some two-block tests failed - check the logs above');
  }
  
  return { conditions, uiTestPassed };
}
