// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpikvtyxwbvytrjeiphr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwaWt2dHl4d2J2eXRyamVpcGhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTk4ODEsImV4cCI6MjA2MzQ5NTg4MX0.uEdnbEPfTRWXfS_v2e_W4ntRkGe5FUcXTBse_nO2LNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);