// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyedubpevrdwsadvnrir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5ZWR1YnBldnJkd3NhZHZucmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTEyMTUsImV4cCI6MjA2NjE4NzIxNX0.C8d181iS0BdSWBSkundhc07zcXo2Ne0fP4YHsrZw8jc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);